name: "CI"

on: [pull_request]

jobs:
  build:
    name: "Build, lint, and test"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "Install dependencies"
        run: bun install

      - name: "Check format"
        run: bun run format:check

      - name: "Build"
        run: bun run build

      - name: "Lint"
        run: bun run lint
